name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          # This context path is correct for our project structure
          context: ./src/app
          file: ./src/app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/model-server:latest, ${{ secrets.DOCKERHUB_USERNAME }}/model-server:${{ github.sha }}

  lint-and-validate:
    name: Lint and Validate Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      - name: Lint Helm chart
        run: helm lint ./helm/model-server

  deploy-to-staging:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    needs: [build-and-push, lint-and-validate]
    steps:
      - name: Simulate Deployment to Staging
        run: |
          echo "Simulating deployment to Staging Kubernetes Cluster..."
          echo "COMMAND THAT WOULD RUN:"
          echo "helm upgrade --install model-server-staging ./helm/model-server --set image.tag=${{ github.sha }} --namespace staging"
          echo "Deployment to staging simulated successfully."

  deploy-to-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-to-staging
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Simulate Deployment to Production
        run: |
          echo "Simulating deployment to Production Kubernetes Cluster..."
          echo "COMMAND THAT WOULD RUN:"
          echo "helm upgrade --install model-server-prod ./helm/model-server --set image.tag=${{ github.sha }} --namespace production"
          echo "Deployment to production simulated successfully."
